# Configure main menu and social menu

[[main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1
  [main.params]
    icon = "fa-solid fa-home"

[[main]]
  identifier = "categories"
  name = "Categories"
  url = "/categories/"
  weight = 2
  [main.params]
    icon = "fa-solid fa-folder-tree"

[[main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"
  weight = 3
  [main.params]
    icon = "fa-solid fa-tags"

[[main]]
  identifier = "links"
  name = "Links"
  url = "/links/"
  weight = 4
  [main.params]
    icon = "fa-solid fa-link"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/LoveOrange"

[social.params]
icon = "brand-github"

[[social]]
identifier = "leetcode"
name = "LeetCode"
url = "https://leetcode.cn/u/linsama/"

[social.params]
icon = "brand-leetcode"
