# FixIt theme general parameters
defaultTheme = "auto"
dateFormat = "2006-01-02"
title = "Linsama's Blog"
description = "Linsama's Personal blog"
customCSS = ["css/custom.scss"]

[author]
  name = "Linsama"
  avatar = "/img/avatar.png"

[header]
  desktopMode = "fixed"
  mobileMode = "auto"
  [header.title]
    name = "Linsama"
    typeit = false
  [header.subtitle]
    typeit = false

[footer]
  enable = true
  [footer.hugo]
    enable = true
  [footer.theme]
    enable = true

[page]
  twemoji = true
  lightgallery = true
  [page.toc]
    enable = true
  [page.code]
    copy = true
    maxShownLines = 50

[typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "|"
  duration = -1
