description = "Linsama's Personal blog"
opengraph = true
twitter_cards = false
readmore = false
authorbox = true
pager = true
post_meta = ["date", "categories"]
mainSections = ["posts", "post"]

[logo]
  subtitle = "Nice to meet you ðŸ˜Š"

[sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist"]

[widgets]
  recent_num = 5
  tags_counter = true

[thumbnail]
  visibility = ["list", "post"]
